Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.hostname = "harikube-openshift"

  config.ssh.insert_key = false

  config.vm.provision "shell", inline: <<-SHELL
    set -euxo pipefail

    dnf install -y podman libvirt libvirt-daemon-kvm qemu-kvm NetworkManager iptables-services

    modprobe br_netfilter
    echo br_netfilter >> /etc/modprobe.d/br_netfilter.conf

    sysctl -w net.ipv4.ip_forward=1
    echo 'net.ipv4.ip_forward = 1' > /etc/sysctl.d/oip_forward
    sysctl -w net.ipv4.conf.eth0.route_localnet=1
    echo 'net.ipv4.conf.eth0.route_localnet = 1' > /etc/sysctl.d/route_localnet
    sysctl -p

    iptables -I INPUT 1 -p tcp -d 127.0.0.1 --dport 6443 -j ACCEPT
    iptables -t nat -A OUTPUT -p tcp -m addrtype --dst-type LOCAL --dport 6443 -j DNAT --to-destination 127.0.0.1:6443
    iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 6443 -j DNAT --to-destination 127.0.0.1:6443
    iptables-save > /etc/sysconfig/iptables

    touch /var/lib/systemd/linger/vagrant

    systemctl daemon-reload
    systemctl enable --now libvirtd iptables

    echo 'export PATH="/home/vagrant/.crc/bin/oc:$(find /opt -type d -name crc*):$PATH"' >> /etc/profile
    echo 'alias kubectl=oc' >> /etc/profile
    echo 'alias docker="sudo podman"' >> /etc/profile
  SHELL

  config.vm.provider :libvirt do |lv|
    lv.uri = "qemu:///system"
    lv.cpus = 8
    lv.memory = 8192
    lv.machine_virtual_size = 40
    lv.cpu_mode = "host-passthrough"
    lv.nic_model_type = "virtio"
    lv.driver = "kvm"
  end
end