apiVersion: v1
kind: Namespace
metadata:
  name: harikube
  labels:
    harikube.info/harikube-middleware: enabled
    harikube.info/harikube-apiserver: enabled
    harikube.info/harikube-controllermanager: enabled
    harikube.info/harikube: enabled
