apiVersion: v2
name: harikube-helm-charts
description: A Helm chart for HariKube
icon: https://avatars.githubusercontent.com/u/239047927?s=200&v=4

type: application

version: 1.15.0-oss

appVersion: 1.15.0

kubeVersion: ">=1.34.0-0"

dependencies:
- name: vcluster
  version: "0.32.1"
  repository: "https://charts.loft.sh"
