apiVersion: v1
kind: Namespace
metadata:
  name: kine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kine-db-pvc
  namespace: kine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kine
  namespace: kine
  labels:
    app: kine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kine
  template:
    metadata:
      labels:
        app: kine
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm64
                    - amd64
                    - s390x
                    - ppc64le
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: kine
        image: quay.io/harikube/kine:#VERSION#
        imagePullPolicy: IfNotPresent
        args:
        - --listen-address=0.0.0.0:2379
        - --datastore-max-idle-connections=5
        - --datastore-max-open-connections=90
        - --datastore-connection-max-lifetime=5m
        - --endpoint=sqlite:///db/main.db?_journal=WAL&cache=shared
        ports:
        - containerPort: 2379
          name: api-port
        - containerPort: 8080
          name: metrics
        volumeMounts:
        - name: db-storage
          mountPath: /db
        - name: tmp
          mountPath: /tmp
        livenessProbe:
          grpc:
            port: 2379
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          grpc:
            port: 2379
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 1Gi
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: kine-db-pvc
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kine-svc
  namespace: kine
spec:
  type: ClusterIP 
  selector:
    app: kine
  ports:
    - name: api
      protocol: TCP
      port: 2379
      targetPort: api-port
---
apiVersion: v1
kind: Service
metadata:
  name: kine-metrics
  namespace: kine
  labels:
    app: kine
    app.kubernetes.io/component: metrics 
spec:
  type: ClusterIP 
  selector:
    app: kine
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: metrics
