apiVersion: v1
kind: Namespace
metadata:
  name: harikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harikube-db-pvc
  namespace: harikube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harikube-middleware
  namespace: harikube
  labels:
    app: harikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harikube
  template:
    metadata:
      labels:
        app: harikube
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm64
                    - amd64
                    - s390x
                    - ppc64le
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: harikube
        image: quay.io/harikube/harikube:#VERSION#
        imagePullPolicy: IfNotPresent
        args:
        - --listen-address=0.0.0.0:2379
        - --server-cert-file=/etc/harikube-middleware-crt/tls.crt
        - --server-key-file=/etc/harikube-middleware-crt/tls.key
        - --datastore-max-idle-connections=5
        - --datastore-max-open-connections=9
        - --datastore-connection-max-lifetime=5m
        - --endpoint=sqlite:///db/main.db?_journal=WAL&cache=shared
        ports:
        - containerPort: 2379
          name: api-port
        - containerPort: 8080
          name: metrics
        volumeMounts:
        - name: db-storage
          mountPath: /db
        - mountPath: /etc/harikube-middleware-crt
          name: harikube-middleware-crt
          readOnly: true
        - name: tmp
          mountPath: /tmp
        livenessProbe:
          httpGet:
            scheme: HTTPS
            port: 8080
            path: /metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            scheme: HTTPS
            port: 8080
            path: /metrics
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 1Gi
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: harikube-db-pvc
      - name: harikube-middleware-crt
        secret:
          secretName: harikube-middleware-crt
      - name: harikube-middleware-pvc
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: harikube-middleware-svc
  namespace: harikube
spec:
  type: ClusterIP 
  selector:
    app: harikube
  ports:
    - name: api
      protocol: TCP
      port: 2379
      targetPort: api-port
---
apiVersion: v1
kind: Service
metadata:
  name: harikube-metrics-svc
  namespace: harikube
  labels:
    app: harikube
    app.kubernetes.io/component: metrics 
spec:
  type: ClusterIP 
  selector:
    app: harikube
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: metrics
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: harikube
  name: harikube-middleware-issuer
  namespace: harikube
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: harikube
  name: harikube-middleware-crt
  namespace: harikube
spec:
  dnsNames:
  - localhost
  - harikube-middleware-svc
  - harikube-middleware-svc.harikube
  - harikube-middleware-svc.harikube.svc
  - harikube-middleware-svc.harikube.cluster.local
  - harikube-middleware-svc.harikube.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: harikube-middleware-issuer
  secretName: harikube-middleware-crt
---
