name: E2E Tests

on:
  push:
    branches: [main, master]
    paths-ignore:
      - "**.md"
      - ".github/workflows/actionlint.yaml"
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "**.md"
      - ".github/workflows/actionlint.yaml"
  
jobs:
  e2e-test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'

      - name: E2E Tests API
        run: devbox run make -C test/e2e build test
        env:
          TAG: e2e
          KINE_TYPE: api

      - name: E2E Tests Workload
        run: devbox run make -C test/e2e build test
        env:
          TAG: e2e
          KINE_TYPE: workload