name: Helm E2E

on:
  push:
    branches-ignore:
    - release-v**
    - rc-v**
    - beta-v**
    - alpha-v**
    - dev-v**

  pull_request:
    branches: [main]
  
jobs:
  helm-test:
    name: Helm test
    if: ${{ !contains(github.event.head_commit.message, '+RKE2') && !contains(github.event.head_commit.message, '+OS') }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.15.0
        with:
          enable-cache: 'true'

      - name: Helm Tests
        run: devbox run make -C test/helm build setup-test _load _deploy
        env:
          TAG: helm

      - name: Helm Test
        run: devbox run make -C test/helm test

      - name: Helm Cleanup Tests
        if: always()
        run: devbox run make -C test/helm cleanup-test
