name: RKE2 Tests

on:
  push:
    branches: [main, master]
    paths-ignore:
      - "**.md"
      - ".github/workflows/actionlint.yaml"
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "**.md"
      - ".github/workflows/actionlint.yaml"

concurrency: 
  group: ${{ github.ref_name }}-rke2
  cancel-in-progress: true

env:
  TAG: rke2

jobs:
  rke2-test:
    name: RKE2 Test
    if: contains(github.event.head_commit.message, '+RKE2')
    runs-on: self-hosted
    timeout-minutes: 90
    strategy:
      matrix:
        version: ['v1.36.2+rke2r1']
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: RKE2 Setup Tests
        run: devbox run make -C test/rke2 deps build setup-test _load _deploy
        env:
          RKE2_VERSION: ${{ matrix.version }}

      - name: RKE2 Test Host
        run: devbox run make -C test/rke2 _test-host

      - name: RKE2 Test vCluster
        run: devbox run make -C test/rke2 _test-vcluster

      - name: RKE2 Cleanup Tests
        if: always()
        run: devbox run make -C test/rke2 cleanup-test

